dist: trusty
language: java
jdk: oraclejdk8
cache:
  directories:
  - $HOME/.cache
  - $HOME/.m2

before_script:
  - cp .travis.settings.xml $HOME/.m2/settings.xml

script:
  - mvn -f CM5/pom.xml clean install -q
 
after_success:
  - bash <(curl -s https://codecov.io/bash)
