// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package ru.intertrust.cm.core.gui.impl.markup.cmj41.navigation.client.component.tree.resources;

import com.google.gwt.resources.client.CssResource;

public interface TreeResources extends CssResource {

  @ClassName("Im_box_open")
  String im_box_open();

  @ClassName("Im_dots")
  String im_dots();

  @ClassName("Im_dots_show")
  String im_dots_show();

  @ClassName("Im_has_sub")
  String im_has_sub();

  @ClassName("Im_icon")
  String im_icon();

  @ClassName("Im_item")
  String im_item();

  @ClassName("Im_last_bg")
  String im_last_bg();

  @ClassName("Im_sub")
  String im_sub();

  @ClassName("Im_sub_open")
  String im_sub_open();

  String last_item();

}
